steps:
- task: NodeTool@0
  inputs:
    versionSpec: "8.x"
  displayName: Install node 8

# install dependencies
- script: npm install
  displayName: npm install

# build
- script: npm run build
  displayName: npm run build

- script: npm run units
 
  displayName: npm install,buil and  unit tests
